version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: amaso_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: amaso
      MYSQL_USER: amaso_user
      MYSQL_PASSWORD: amaso_password
    volumes:
      - db_data:/var/lib/mysql
      - ./amaso.sql:/docker-entrypoint-initdb.d/01-amaso.sql:ro
    ports:
      - "3306:3306"
    networks:
      - amaso_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: amaso_backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - php_storage:/var/www/storage
    ports:
      - "8000:8000"
      - "5173:5173"  # Vite dev server
    environment:
      - DB_HOST=db
      - DB_DATABASE=amaso
      - DB_USERNAME=amaso_user
      - DB_PASSWORD=amaso_password
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - amaso_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: amaso_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - backend
    networks:
      - amaso_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx Reverse Proxy (Optional for production)
  nginx:
    image: nginx:alpine
    container_name: amaso_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - amaso_network

networks:
  amaso_network:
    driver: bridge

volumes:
  db_data:
    driver: local
  php_storage:
    driver: local